import 'package:hive/hive.dart';

// This part is auto-generated by the build_runner.
// We will run the generator command later.
part 'task.g.dart';

@HiveType(typeId: 0)
class Task extends HiveObject {
  // A unique identifier for each task.
  // Using HiveField(0) to mark this as the first field.
  @HiveField(0)
  late String id;

  // The title or description of the task.
  // Marked as the second field.
  @HiveField(1)
  late String title;

  // The completion status of the task.
  // Marked as the third field.
  @HiveField(2)
  late bool isCompleted;

  // Constructor to create a new Task instance.
  Task({
    required this.id,
    required this.title,
    this.isCompleted = false,
  });
}
