import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';

// We will create these files in the next steps.
import 'models/task.dart';
import 'providers/task_provider.dart';
import 'screens/home_screen.dart';

// The main entry point of the application.
void main() async {
  // Ensure that Flutter bindings are initialized before calling native code.
  WidgetsFlutterBinding.ensureInitialized();

  // Get the application documents directory for storing Hive database.
  final appDocumentDir = await getApplicationDocumentsDirectory();

  // Initialize Hive in the specified directory.
  await Hive.initFlutter(appDocumentDir.path);

  // Register the adapter for the Task model.
  // The TaskAdapter will be generated by build_runner.
  Hive.registerAdapter(TaskAdapter());

  // Open the box where tasks will be stored.
  await Hive.openBox<Task>('tasks');

  // Run the Flutter application.
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Using ChangeNotifierProvider to make the TaskProvider available
    // to all widgets in the subtree.
    return ChangeNotifierProvider(
      create: (context) => TaskProvider(),
      child: MaterialApp(
        title: 'ToDoly Flutter',
        debugShowCheckedModeBanner: false,
        
        // Define the light theme for the application.
        theme: ThemeData(
          brightness: Brightness.light,
          primarySwatch: Colors.blue,
          scaffoldBackgroundColor: const Color(0xFFF5F5F5),
          appBarTheme: AppBarTheme(
            backgroundColor: Colors.blue,
            elevation: 0,
            titleTextStyle: GoogleFonts.vazirmatn(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          textTheme: TextTheme(
            bodyLarge: GoogleFonts.vazirmatn(color: Colors.black87),
            bodyMedium: GoogleFonts.vazirmatn(color: Colors.black54),
            titleLarge: GoogleFonts.vazirmatn(fontWeight: FontWeight.bold),
          ),
          useMaterial3: true,
        ),

        // Define the dark theme for the application.
        darkTheme: ThemeData(
          brightness: Brightness.dark,
          primarySwatch: Colors.blue,
          scaffoldBackgroundColor: const Color(0xFF212121),
          appBarTheme: AppBarTheme(
            backgroundColor: const Color(0xFF2C2C2C),
            elevation: 0,
            titleTextStyle: GoogleFonts.vazirmatn(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          textTheme: TextTheme(
            bodyLarge: GoogleFonts.vazirmatn(color: Colors.white),
            bodyMedium: GoogleFonts.vazirmatn(color: Colors.white70),
            titleLarge: GoogleFonts.vazirmatn(fontWeight: FontWeight.bold, color: Colors.white),
          ),
          useMaterial3: true,
        ),

        // Automatically select theme based on system settings.
        themeMode: ThemeMode.system,

        // The home screen of the application.
        // We will create this widget in the next step.
        home: const HomeScreen(),
      ),
    );
  }
}
